### PR TITLE
[RouterHelper] projectOutputPinToINTNode() to breadth-first-search

### LINKED ISSUE #558: RWRoute RouteHelper fails to find the INT tile entry node from a BITSLICE_CONTROL site pin
The method `RouteHelper.projectOutputPinToINTNode()` has not been tested in RWRoute for `BITSLICE_CONTROL` site pins and does not find the INT tile entry node for the beginning of a route.  For example, the site pin `TX_T_OUT` when queried, the method returns `null` when it should return the node `INT_INTF_L_CMT_X182Y90/LOGIC_OUTS_R19`.  In Vivado, we can see that the INT entry node (shown in green) does exist:

image

The method needs to account for the pip connection between the two nodes as shown in blue.

EDIT: For future contributors who will work on this -- a test demonstrating this failure is at https://github.com/Xilinx/RapidWright/pull/559

### PR DESCRIPTION
**Pull request by eddieh-xlnx**
Much like `projectInputPinToINTNode()` as this seems necessary for Versal I/Os (and even fixed #558!)

Without this, in an upcoming `PartialRouter` test with `picoblaze_2022.2.dcp`, the projected result is not the same as Vivado's solution thereby leading to an unroutable situation.

### CODE REVIEW

File: src/com/xilinx/rapidwright/rwroute/RouterHelper.java [hunk 1]
```diff
@@ -143,27 +144,18 @@ public static boolean isExternalConnectionToCout(SitePinInst source, SitePinInst
...
-            List<Node> downhillNodes = node.getAllDownhillNodes();
-            if (downhillNodes.isEmpty()) {
-                continue;
-            }
-
-            queue.clear();
-            for (Node downhill : downhillNodes) {
+            for (Node downhill : node.getAllDownhillNodes()) {
                 if (Utils.isInterConnect(downhill.getTile().getTileTypeEnum())) {
+                    // Return node that has at laest one downhill in the INT tile
```
Comment (eddieh-xlnx) [inline src/com/xilinx/rapidwright/rwroute/RouterHelper.java:158]:
```suggestion
                    // Return node that has at least one downhill in the INT tile
```
