### PR TITLE
RelocationTools fixes and more robust testing

### LINKED ISSUE #393: RelocationTools.revertRouting does not really revert
https://github.com/Xilinx/RapidWright/blob/a34c0d71521a758e757056714ff0503de28f0c71/src/com/xilinx/rapidwright/design/tools/RelocationTools.java#L304-L308

is effectively a NOOP because it's modifying the list of references (to the same set of references) but not actually changing the referent.

### PR DESCRIPTION
**Pull request by eddieh-xlnx**
Fixes #393 too, a feature that is no longer relevant as of #808.

### CODE REVIEW

File: src/com/xilinx/rapidwright/design/tools/RelocationTools.java [hunk 1]
```diff
@@ -238,25 +235,27 @@ public static boolean relocate(Design design,
...
 
+            Collection<SitePinInst> pins = n.getPins();
             SitePinInst src = n.getSource();
             if (src != null && !oldSite.containsKey(src.getSiteInst())) {
-                System.out.println("INFO: Unrouting Net '" + n.getName() + "' since output SiteInstPin '" +
-                        src + "' does not belong to SiteInsts to be relocated");
-                n.unroute();
+                for (SitePinInst spi : pins) {
+                    if (oldSite.containsKey(spi.getSiteInst())) {
+                        // Source is not reloacted, but at least one pin inside site insts to be relocated
```
Comment (clavin-xlnx) [inline src/com/xilinx/rapidwright/design/tools/RelocationTools.java:250]:
```suggestion
                        // Source is not relocated, but at least one pin inside site insts to be relocated
```

**Review by clavin-xlnx — APPROVED** [review]
