### PR TITLE
DesignTools.createCeSrRstPinsToVCC() to skip non-SLICE FFs

### LINKED ISSUE #738: RWRoute fails with null pointer exception on placement produced with nextpnr
Running RWRoute in `--nonTimingDriven` mode on a DCP containing a placement produced by nextpnr-fpga_interchange produced the following error:
```
/group/zircon2/zakn/rapidwright_clean/RapidWright/bin/rapidwright RWRoute gnl_2_4_7_2.0_gnl_2000_03_7_80_80_nextpnr_placed.dcp gnl_2k_RWRoute_routed.dcp --nonTimingDriven
==============================================================================
==                                 RWRoute                                  ==
==============================================================================
==============================================================================
==    Reading DCP: gnl_2_4_7_2.0_gnl_2000_03_7_80_80_nextpnr_placed.dcp     ==
==============================================================================
 XML Parse & Device Load:     1.023s
    (Read PhysDB Caches):            (    0.131s)
Running job [1] /home/zakn/bin/vivado -mode batch -source readable.tcl in /group/zircon2/zakn/nextpnr_install/autoflow/archive/202306301015/gnl_2_4_7_2.0_gnl_2000_03_7_80_80_nextpnr_placed.dcp.edf/gnl_2_4_7_2.0_gnl_2000_03_7_80_80_nextpnr_placed.edf_readable_edif_12346395580872443603
   (Read PhysDB Routing):            (    0.054s)
 (Read PhysDB Placement):            (    0.148s)
(Read PhysDB Finalizing):            (    0.004s)
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 1 running, 0 not yet started...
Waiting on 0 not yet started...
            (EDIF Parse):            (   58.586s)
   Read Netlist & PhysDB:    58.589s
------------------------------------------------------------------------------
         [No GC] *Total*:    59.612s
WARNING: Not masking nodes across RCLK could result in delay optimism.
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.xilinx.rapidwright.util.Pair.getSecond()" because "sitePinNames" is null
	at com.xilinx.rapidwright.design.DesignTools.createCeSrRstPinsToVCC(DesignTools.java:2874)
	at com.xilinx.rapidwright.design.DesignTools.createPossiblePinsToStaticNets(DesignTools.java:2772)
	at com.xilinx.rapidwright.rwroute.RWRoute.preprocess(RWRoute.java:186)
	at com.xilinx.rapidwright.rwroute.RWRoute.preprocess(RWRoute.java:191)
	at com.xilinx.rapidwright.rwroute.RWRoute.routeDesign(RWRoute.java:1787)
	at com.xilinx.rapidwright.rwroute.RWRoute.routeDesign(RWRoute.java:1778)
	at com.xilinx.rapidwright.rwroute.RWRoute.routeDesignWithUserDefinedArguments(RWRoute.java:1770)
	at com.xilinx.rapidwright.rwroute.RWRoute.main(RWRoute.java:1815)
	at com.xilinx.rapidwright.MainEntrypoint.main(MainEntrypoint.java:214)
```
note that the DCP is at least minimally well formatted since vivado is able to open it and partially route the design. The vivado router fails to route all nets in the design, but does crash. I think ideally RWRoute would do something similar, or at least detect that the design is unrouteable and quit with an informative fatal error instead of crashing.

The process to produce this DCP is somewhat convoluted, but is basically as follows:

1. begin with a benchmark DCP
2. with vivado place IO ports, write an XDC with IO constraints, and emit a verilog netlist
3. use yosys to synthesize the verilog netlist
4. convert the yosys result to an FPGAIF netlist via python_fpga_interchange
5. use nextpnr-fpga_interchange to place and route the FPGAIF netlist
6. use rapidwright to convert the placed and routed FPGAIF physical netlist emitted by nextpnr-fpga_interchange to a DCP
7. unroute this DCP with vivado
8. route the unrouted DCP with RWRoute

The follow zip archive includes the DCP that produced this error.
[example_dcps.zip](https://github.com/Xilinx/RapidWright/files/11919391/example_dcps.zip)

The included zip archive contains the output of step 7, which produces the RWRoute output presented above. The initial DCP used in step 1 was `gnl_2_4_7_2.0_gnl_2000_03_7_80_80.dcp` from the gnl timing design benchmarks. Note that the zip archive also includes another step 7 DCP that produces a similar RWRoute error.

### PR DESCRIPTION
**Pull request by eddieh-xlnx**
CC @zakn-amd 

Fixes #738, with test based on smaller of the two attached testcases. Both exhibit the same failure where `DesignTools.createCeSrRstPinsToVCC()` was trying to work on a Laguna flop.

### CODE REVIEW

File: src/com/xilinx/rapidwright/design/DesignTools.java [hunk 1]
```diff
@@ -3092,6 +3092,9 @@ public static void createCeSrRstPinsToVCC(Design design) {
         for (Cell cell : design.getCells()) {
             if (isUnisimFlipFlopType(cell.getType())) {
                 SiteInst si = cell.getSiteInst();
+                if (!Utils.isSLICE(si)) {
+                    continue;
+                }
                 BEL bel = cell.getBEL();
                 Pair<String, String> sitePinNames = pinMapping.get(bel.getBELType());
                 String[] pins = new String[] {"CE", "SR"};
```
Comment (clavin-xlnx) [inline src/com/xilinx/rapidwright/design/DesignTools.java:3100]: Not part of this PR, but should we move this `new String[]` to above, outside the loop?

**Review by clavin-xlnx — APPROVED** [review]

File: src/com/xilinx/rapidwright/design/DesignTools.java (hunk 1 above)
Comment (eddieh-xlnx) [reply src/com/xilinx/rapidwright/design/DesignTools.java]: Might as well do it here!
