### PR TITLE
Fix DesignTools.makePhysNetNamesConsistent() 

### LINKED ISSUE #701: RWRoute only assigns a single SitePinInst to the ground net.
I have an unrouted design checkpoint (shared below). When I attempted to route using RWRoute  (`rapidwright RWRoute cntr-preRouted.dcp cntr-routed.dcp --nonTimingDriven`), it only routes the GND net to a single site pin leaving the rest of the net unrouted.

[cntr-preRouted.zip](https://github.com/Xilinx/RapidWright/files/11710549/cntr-preRouted.zip)

### PR DESCRIPTION
**Pull request by eddieh-xlnx**
By transforming logical static nets named `<const{0,1}>` into physical static nets `GLOBAL_LOGIC{0,1}`

Fixes #701.

CC: @haydenc-amd

### CODE REVIEW

File: test/src/com/xilinx/rapidwright/design/TestDesignTools.java [hunk 1]
```diff
@@ -948,4 +948,34 @@ public void testCreateCeSrRstPinsToVCC(String deviceName, String location, Strin
...
+    public void testMakePhysNetNamesConsistentLogicalVccGnd() {
+        Design design = RapidWrightDCP.loadDCP("bug701.dcp");
+
+        // Design has no GLOBAL_LOGIC{0,1}
+        Assertions.assertNull(design.getNet(Net.VCC_NET));
+        Assertions.assertNull(design.getNet(Net.GND_NET));
+
+        DesignTools.makePhysNetNamesConsistent(design);
+
+        // Check those nets were created
```
Comment (eddieh-xlnx) [inline test/src/com/xilinx/rapidwright/design/TestDesignTools.java:962]:
```suggestion
        // Check those nets were created and all sitewires
        // were switched over correctly
```

**Review by clavin-xlnx — APPROVED** [review]
